### ISSUE TITLE
I want to add questions and solutions 

### ISSUE THREAD

**Issue by NIKHILSINGH1510** [YashThakare/DSA_Uplift_Project#476]

**Comment by SwarnimaShishodia** [comment]
Hi Nikhil, are you participant for batch-1 ?

**Comment by NIKHILSINGH1510** [comment]
> Hi Nikhil, are you participant for batch-1 ?

yes

**Comment by SwarnimaShishodia** [comment]
> > Hi Nikhil, are you participant for batch-1 ?
> 
> yes

I will let you know, after discussing with team.

**Comment by NIKHILSINGH1510** [comment]
> > > Hi Nikhil, are you participant for batch-1 ?
> > 
> > 
> > yes
> 
> I will let you know, after discussing with team.

sure

**Comment by SwarnimaShishodia** [comment]
Your name is not in repo. Can you just sent a msg on discord channel .

> > > > Hi Nikhil, are you participant for batch-1 ?
> > > 
> > > 
> > > yes
> > 
> > 
> > I will let you know, after discussing with team.
> 
> sure

Your name is not in repo. Can you just sent a msg on discord channel ?
